apiVersion: v1
items:
- apiVersion: trident.netapp.io/v1
  backendName: comp-ontap-nas1-prod
  backendUUID: e6995f3e-bdfb-4160-a0f7-30c92a6e0f84
  config:
    ontap_config:
      aggregate: ""
      autoExportCIDRs:
      - 10.100.1.0/24
      autoExportPolicy: true
      backendName: comp-ontap-nas1-prod
      backendPools:
      - eyJzdm1VVUlEIjoiMDU3YmY5NmUtYjAwZS0xMWYwLWE5OWMtMDBhMDk4Y2EwZjZiIiwiYWdncmVnYXRlIjoidXMwMl9uYTAxX24wNF9zYXRhNF9lIn0=
      - eyJzdm1VVUlEIjoiMDU3YmY5NmUtYjAwZS0xMWYwLWE5OWMtMDBhMDk4Y2EwZjZiIiwiYWdncmVnYXRlIjoidXMwMl9uYTAxX24wMV9zc2QxIn0=
      - eyJzdm1VVUlEIjoiMDU3YmY5NmUtYjAwZS0xMWYwLWE5OWMtMDBhMDk4Y2EwZjZiIiwiYWdncmVnYXRlIjoidXMwMl9uYTAxX24wMl9zc2QxIn0=
      chapInitiatorSecret: ""
      chapTargetInitiatorSecret: ""
      chapTargetUsername: ""
      chapUsername: ""
      clientCertificate: ""
      clientPrivateKey: ""
      cloneSplitDelay: "10"
      credentials:
        name: comp-ontap-secret-nas1
      dataLIF: 10.100.1.16
      debug: false
      debugTraceFlags: null
      defaults:
        LUKSEncryption: "false"
        adAdminUser: ""
        adaptiveQosPolicy: ""
        encryption: ""
        exportPolicy: <automatic>
        fileSystemType: ext4
        formatOptions: ""
        mirroring: "false"
        nameTemplate: ""
        qosPolicy: ""
        securityStyle: unix
        size: 1G
        skipRecoveryQueue: "false"
        snapshotDir: "false"
        snapshotPolicy: none
        snapshotReserve: ""
        spaceAllocation: "true"
        spaceReserve: none
        splitOnClone: "false"
        tieringPolicy: ""
        unixPermissions: '---rwxrwxrwx'
      denyNewVolumePools: "false"
      disableDelete: false
      emptyFlexvolDeferredDeletePeriod: ""
      flags:
        disaggregated: "false"
        personality: Unified
        sanOptimized: "false"
      flexgroupAggregateList: []
      igroupName: ""
      labels: null
      limitAggregateUsage: ""
      limitVolumePoolSize: ""
      limitVolumeSize: ""
      lunsPerFlexvol: ""
      managementLIF: 10.100.0.210
      nasType: nfs
      nfsMountOptions: ""
      password: secret:comp-ontap-secret-nas1
      qtreePruneFlexvolsPeriod: ""
      qtreeQuotaResizePeriod: ""
      qtreesPerFlexvol: ""
      region: ""
      replicationPolicy: ""
      replicationSchedule: ""
      sanType: iscsi
      smbShare: ""
      storage: null
      storageDriverName: ontap-nas
      storagePrefix: {}
      supportedTopologies: null
      svm: REDHATPOCHET
      trustedCACertificate: ""
      usageHeartbeat: ""
      useCHAP: false
      useREST: null
      userState: ""
      username: secret:comp-ontap-secret-nas1
      version: 1
      zone: ""
  configRef: f955f953-4499-4501-be75-6eb3b5ce2256
  kind: TridentBackend
  metadata:
    creationTimestamp: "2025-12-10T14:41:11Z"
    finalizers:
    - trident.netapp.io
    generateName: tbe-
    generation: 3
    name: tbe-q9x5n
    namespace: trident
    resourceVersion: "52764152"
    uid: 2932bbde-63e7-4c2c-b25d-e66212f725c0
  online: true
  state: online
  userState: normal
  version: "1"
- apiVersion: trident.netapp.io/v1
  kind: TridentBackendConfig
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"trident.netapp.io/v1","kind":"TridentBackendConfig","metadata":{"annotations":{},"name":"comp-ontap-nas1-prod","namespace":"trident"},"spec":{"autoExportCIDRs":["10.100.1.0/24"],"autoExportPolicy":true,"credentials":{"name":"comp-ontap-secret-nas1"},"dataLIF":"10.100.1.16","managementLIF":"10.100.0.210","storageDriverName":"ontap-nas","svm":"REDHATPOCHET","version":1}}
    creationTimestamp: "2025-12-10T14:41:10Z"
    finalizers:
    - trident.netapp.io
    generation: 2
    name: comp-ontap-nas1-prod
    namespace: trident
    resourceVersion: "40575985"
    uid: f955f953-4499-4501-be75-6eb3b5ce2256
  spec:
    autoExportCIDRs:
    - 10.100.1.0/24
    autoExportPolicy: true
    credentials:
      name: comp-ontap-secret-nas1
    dataLIF: 10.100.1.16
    managementLIF: 10.100.0.210
    storageDriverName: ontap-nas
    svm: REDHATPOCHET
    version: 1
  status:
    backendInfo:
      backendName: comp-ontap-nas1-prod
      backendUUID: e6995f3e-bdfb-4160-a0f7-30c92a6e0f84
    deletionPolicy: delete
    lastOperationStatus: Success
    message: Backend 'comp-ontap-nas1-prod' updated
    phase: Bound
- apiVersion: trident.netapp.io/v1
  kind: TridentVersion
  metadata:
    creationTimestamp: "2025-11-05T18:20:26Z"
    finalizers:
    - trident.netapp.io
    generation: 3
    name: trident
    namespace: trident
    resourceVersion: "15565909"
    uid: b6457e63-6f61-48c0-a967-e2bae5159fca
  publications_synced: true
  trident_api_version: "1"
  trident_store_version: crdv1
  trident_version: 25.10.0
- apiVersion: trident.netapp.io/v1
  kind: TridentOrchestrator
  metadata:
    creationTimestamp: "2025-11-17T22:52:51Z"
    generation: 1
    name: trident
    resourceVersion: "43156652"
    uid: d4b60ebd-9258-4b9f-8445-206dfe02e442
  spec:
    IPv6: false
    debug: true
    imagePullSecrets: []
    imageRegistry: ""
    namespace: trident
    nodePrep: []
    silenceAutosupport: false
  status:
    acpVersion: v25.10.0
    currentInstallationParams:
      IPv6: "false"
      acpImage: ""
      autosupportHostname: ""
      autosupportImage: registry.connect.redhat.com/netapp/trident-autosupport@sha256:b273f7c1922ab2273c9b99f22383be88b6511fcd77f34299e9ecb1f85081fb2b
      autosupportInsecure: false
      autosupportProxy: ""
      autosupportSerialNumber: ""
      debug: "true"
      disableAuditLog: "true"
      enableACP: "false"
      enableConcurrency: "false"
      enableForceDetach: "false"
      hostNetwork: false
      httpRequestTimeout: 90s
      httpsMetrics: "false"
      imagePullPolicy: IfNotPresent
      imagePullSecrets: []
      imageRegistry: ""
      iscsiSelfHealingInterval: 5m0s
      iscsiSelfHealingWaitTime: 7m0s
      k8sTimeout: "180"
      kubeletDir: /var/lib/kubelet
      logFormat: text
      logLayers: ""
      logLevel: debug
      logWorkflows: ""
      nodePrep: null
      probePort: "17546"
      resources:
        controller:
          csi-attacher:
            requests:
              cpu: 2m
              memory: 20Mi
          csi-provisioner:
            requests:
              cpu: 2m
              memory: 20Mi
          csi-resizer:
            requests:
              cpu: 3m
              memory: 20Mi
          csi-snapshotter:
            requests:
              cpu: 2m
              memory: 20Mi
          trident-autosupport:
            requests:
              cpu: 1m
              memory: 30Mi
          trident-main:
            requests:
              cpu: 10m
              memory: 80Mi
        node:
          linux:
            node-driver-registrar:
              requests:
                cpu: 1m
                memory: 10Mi
            trident-main:
              requests:
                cpu: 10m
                memory: 60Mi
          windows:
            liveness-probe:
              requests:
                cpu: 2m
                memory: 40Mi
            node-driver-registrar:
              requests:
                cpu: 6m
                memory: 40Mi
            trident-main:
              requests:
                cpu: 10m
                memory: 60Mi
      silenceAutosupport: "false"
      tridentImage: registry.connect.redhat.com/netapp/trident@sha256:59331f85ed657b1af9f8b139f08d6eae00be8d7b404784dbb61c5b5eb3f4d808
    message: Trident installed
    namespace: trident
    status: Installed
    version: v25.10.0
- apiVersion: trident.netapp.io/v1
  deleted: false
  hostInfo:
    os:
      distro: rhcos
      version: "4.18"
    services:
    - NFS
    - nvme
  hostWWPNMap:
    "0x20000025b50a03af":
    - "0x200400a098ca0f6b"
    "0x20000025b50b00bf":
    - "0x200400a098ca0f6b"
  ips:
  - 10.100.0.61
  - 10.130.0.2
  kind: TridentNode
  logLayers: ""
  logLevel: debug
  logWorkflows: ""
  metadata:
    creationTimestamp: "2026-02-07T02:49:16Z"
    finalizers:
    - trident.netapp.io
    generation: 1
    name: rhpoc-mgr01
    namespace: trident
    resourceVersion: "301716491"
    uid: f0e2b62f-3090-437b-b7a4-4c105813e7db
  name: ""
  nodePrep: null
  nqn: nqn.2014-08.org.nvmexpress:uuid:a2a088d5-07c8-47e3-971f-b5a5b9f487e3
  publicationState: clean
- apiVersion: trident.netapp.io/v1
  deleted: false
  hostInfo:
    os:
      distro: rhcos
      version: "4.18"
    services:
    - NFS
    - nvme
  hostWWPNMap:
    "0x20000025b53aa001":
    - "0x200400a098ca0f6b"
    "0x20000025b53bb001":
    - "0x200400a098ca0f6b"
  ips:
  - 10.100.0.62
  - 10.128.0.2
  kind: TridentNode
  logLayers: ""
  logLevel: debug
  logWorkflows: ""
  metadata:
    creationTimestamp: "2025-11-05T18:21:06Z"
    finalizers:
    - trident.netapp.io
    generation: 1
    name: rhpoc-mgr02
    namespace: trident
    resourceVersion: "1184532"
    uid: 1f6a28ca-71a1-48d3-a27e-9efc459f2948
  name: ""
  nodePrep: null
  nqn: nqn.2014-08.org.nvmexpress:uuid:a2a088d5-07c8-47e3-971f-b5a5b9f487e3
  publicationState: clean
- apiVersion: trident.netapp.io/v1
  deleted: false
  hostInfo:
    os:
      distro: rhcos
      version: "4.18"
    services:
    - NFS
    - nvme
  hostWWPNMap:
    "0x20000025b54aa29f":
    - "0x200400a098ca0f6b"
    "0x20000025b54bb29f":
    - "0x200400a098ca0f6b"
  ips:
  - 10.100.0.63
  - 10.129.0.2
  kind: TridentNode
  logLayers: ""
  logLevel: debug
  logWorkflows: ""
  metadata:
    creationTimestamp: "2025-11-05T18:21:07Z"
    finalizers:
    - trident.netapp.io
    generation: 3
    name: rhpoc-mgr03
    namespace: trident
    resourceVersion: "51249390"
    uid: 582cb774-b513-46e9-b63a-ef6f5b3846ab
  name: ""
  nodePrep: null
  nqn: nqn.2014-08.org.nvmexpress:uuid:a2a088d5-07c8-47e3-971f-b5a5b9f487e3
  publicationState: clean
- apiVersion: trident.netapp.io/v1
  deleted: false
  hostInfo:
    os:
      distro: rhcos
      version: "4.18"
    services:
    - NFS
    - nvme
  hostWWPNMap:
    "0x20000025b50a028f":
    - "0x200400a098ca0f6b"
    "0x20000025b50b00cf":
    - "0x200400a098ca0f6b"
  ips:
  - 10.100.0.71
  - 10.100.1.71
  - 10.128.2.2
  kind: TridentNode
  logLayers: ""
  logLevel: debug
  logWorkflows: ""
  metadata:
    creationTimestamp: "2026-01-08T02:48:48Z"
    finalizers:
    - trident.netapp.io
    generation: 2
    name: rhpoc-us02-wrkr01
    namespace: trident
    resourceVersion: "96701550"
    uid: d0310512-7267-4ece-b447-ee4eb01ce5e2
  name: ""
  nodePrep: null
  nqn: nqn.2014-08.org.nvmexpress:uuid:a2a088d5-07c8-47e3-971f-b5a5b9f487e3
  publicationState: clean
- apiVersion: trident.netapp.io/v1
  deleted: false
  hostInfo:
    os:
      distro: rhcos
      version: "4.18"
    services:
    - NFS
    - nvme
  hostWWPNMap:
    "0x20000025b53aa003":
    - "0x200400a098ca0f6b"
    "0x20000025b53bb003":
    - "0x200400a098ca0f6b"
  ips:
  - 10.100.0.72
  - 10.100.1.72
  - 10.129.2.2
  kind: TridentNode
  logLayers: ""
  logLevel: debug
  logWorkflows: ""
  metadata:
    creationTimestamp: "2026-01-14T14:58:11Z"
    finalizers:
    - trident.netapp.io
    generation: 2
    name: rhpoc-us02-wrkr02
    namespace: trident
    resourceVersion: "100345151"
    uid: ba2665cb-ef28-4400-8736-d4a867644a76
  name: ""
  nodePrep: null
  nqn: nqn.2014-08.org.nvmexpress:uuid:a2a088d5-07c8-47e3-971f-b5a5b9f487e3
  publicationState: clean
- apiVersion: trident.netapp.io/v1
  deleted: false
  hostInfo:
    os:
      distro: rhcos
      version: "4.18"
    services:
    - NFS
    - nvme
  hostWWPNMap:
    "0x20000025b54aa24f":
    - "0x200400a098ca0f6b"
    "0x20000025b54bb24f":
    - "0x200400a098ca0f6b"
  ips:
  - 10.100.0.73
  - 10.100.1.73
  - 10.130.2.2
  kind: TridentNode
  logLayers: ""
  logLevel: debug
  logWorkflows: ""
  metadata:
    creationTimestamp: "2026-01-14T17:35:19Z"
    finalizers:
    - trident.netapp.io
    generation: 2
    name: rhpoc-us02-wrkr03
    namespace: trident
    resourceVersion: "100428459"
    uid: b628fd9e-5263-4d8d-8c9d-d4ee46a7b92f
  name: ""
  nodePrep: null
  nqn: nqn.2014-08.org.nvmexpress:uuid:a2a088d5-07c8-47e3-971f-b5a5b9f487e3
  publicationState: clean
kind: List
metadata:
  resourceVersion: ""
