apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: worker-dns-config
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ''
  desiredState:
    # DNS Servers - Primary resolution method
    dns-resolver:
      config:
        search:
          - example.com
          - storage.example.com
        server:
          - 10.100.0.10    # Primary DNS (with NetApp delegation)
          - 10.100.0.11    # Secondary DNS (backup)
          - 10.100.1.16    # Node1_Lif1 us02-na01-n01


          # 10.100.1.16/24       us02-na01-n01
          # 10.100.1.17/24       us02-na01-n02
          # 10.100.1.18/24       us02-na01-n03 
          # 10.100.1.19/24       us02-na01-n04 
          # search comp-poc-rh01.rhpoc.int
